FROM python:3.11-slim
WORKDIR /app

# Ensure pip is up to date and install common dependencies
COPY common-requirements.txt .
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r common-requirements.txt
