from django.urls import path
from .views import (
    BookListHTMLAPIView,
    BooksGatewayAPIView,
    CartAddGatewayAPIView,
    ClothesGatewayAPIView,
    CartHTMLAPIView,
    CustomersGatewayAPIView,
    LoginGatewayAPIView,
    OrdersGatewayAPIView,
    ProductReviewsGatewayAPIView,
    ProductReviewStatsGatewayAPIView,
    ProxyAPIView,
    RegisterGatewayAPIView,
    SearchGatewayAPIView,
    EcomChatGatewayAPIView,
    EcomRecommendGatewayAPIView,
    EcomTrackGatewayAPIView,
)

urlpatterns = [
    path("books/", BooksGatewayAPIView.as_view()),
    path("clothes/", ClothesGatewayAPIView.as_view()),
    path("customers/", CustomersGatewayAPIView.as_view()),
    path("orders/", OrdersGatewayAPIView.as_view()),
    path("cart/add/", CartAddGatewayAPIView.as_view()),
    path("products/<int:product_id>/reviews/", ProductReviewsGatewayAPIView.as_view()),
    path("products/<int:product_id>/reviews/stats/", ProductReviewStatsGatewayAPIView.as_view()),
    path("api/products/<int:product_id>/reviews/", ProductReviewsGatewayAPIView.as_view()),
    path("api/products/<int:product_id>/reviews/stats/", ProductReviewStatsGatewayAPIView.as_view()),
    path("auth/register/", RegisterGatewayAPIView.as_view()),
    path("auth/login/", LoginGatewayAPIView.as_view()),
    path("web/books/", BookListHTMLAPIView.as_view()),
    path("web/carts/<int:cart_id>/", CartHTMLAPIView.as_view()),
    path("search/", SearchGatewayAPIView.as_view()),
    path("chat/", EcomChatGatewayAPIView.as_view()),
    path("recommend/<str:user_id>/", EcomRecommendGatewayAPIView.as_view()),
    path("track/", EcomTrackGatewayAPIView.as_view()),
    path("api/<str:service>/", ProxyAPIView.as_view()),
    path("api/<str:service>/<path:subpath>", ProxyAPIView.as_view()),
]
